apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube.fullname" . }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 9000
  selector:
    {{- include "sonarqube.selectorLabels" . | nindent 4 }}
  type: ClusterIP